Ronja/cell classification
lozadaa-chalmers/transformer-bio pull request #17
Opened 2023-11-28 13:02 UTC by ronjakh

Pull request, I added comments on the functions.

2023-11-28 13:30 UTC, lozadaa-chalmers requested changes
Before anything, you're missing tests!

2023-12-07 08:50 UTC, lozadaa-chalmers requested changes

2023-12-07 12:34 UTC, ronjakh commented on tasks/data_handling/cell_classification.py
> +    scored_adata.obs[classification_key] = max_class_column
Do you mean in the dictionary? Now it just implements the name in the file, for example 'suva_ac_PMID_31327527'. Do you think it is so unlikely that we will use this method for any other classes, and therefore should hard code it in?

2023-12-07 15:22 UTC, lozadaa-chalmers commented on tasks/data_handling/tests/test_cell_classification.py
> +        c1_test[cell] = (sum(X_data[cell, 0:3]) / 3 - sum(X_data[(cell + 1) % 3, 0:3]) / 6 -
Why is this working? Are we supposed to sample genes or cells?

2023-12-08 09:09 UTC, merged